/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CraftmanRouteImport } from './routes/craftman'
import { Route as ViseRouteImport } from './routes/vise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftmanRoute = CraftmanRouteImport.update({
  id: '/craftman',
  path: '/craftman',
  getParentRoute: () => rootRouteImport,
} as any)
const ViseRoute = ViseRouteImport.update({
  id: '/vise',
  path: '/vise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/craftman': typeof CraftmanRoute
  '/vise': typeof ViseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/craftman': typeof CraftmanRoute
  '/vise': typeof ViseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/craftman': typeof CraftmanRoute
  '/vise': typeof ViseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/craftman' | '/vise'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/craftman' | '/vise'
  id: '__root__' | '/' | '/about' | '/craftman' | '/vise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CraftmanRoute: typeof CraftmanRoute
  ViseRoute: typeof ViseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftman': {
      id: '/craftman'
      path: '/craftman'
      fullPath: '/craftman'
      preLoaderRoute: typeof CraftmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vise': {
      id: '/vise'
      path: '/vise'
      fullPath: '/vise'
      preLoaderRoute: typeof ViseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CraftmanRoute: CraftmanRoute,
  ViseRoute: ViseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
